export enum CandidateStatus {
    APPLIED = 'APPLIED',
    HIRED = 'HIRED',
    IN_INTERVIEW = 'IN_INTERVIEW',
    ON_PROGRESS = 'ON_PROGRESS',
    QUALIFIED = 'QUALIFIED',
    REJECTED = 'REJECTED',
    NOT_APPLIED ='NOT_APPLIED'
  }
  